on:
  repository_dispatch:
    types:
      - UPDATE_PACKAGE

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print event payload
        run: |
          echo '${{toJson(github.event.client_payload)}}'
          node ./scripts/update-data.js '${{toJson(github.event.client_payload)}}'

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.event.sender.login }}"
          git config --global user.email "${{ github.event.sender.login }}@unknown.com"

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Commit changes"
          git push origin HEAD:refs/heads/master
      
      - name: Build nextjs
        uses: ./.github/workflows/nextjs.yml
