on:
  repository_dispatch:
    types:
      - CREATE_PACKAGE

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print event payload
        run: |
          echo '${{ toJson(github.event) }}'
